version: "3.7"
services:
  server:
    network_mode: host
    image: oznu/homebridge:2022-02-09@sha256:b495951642d36406d83dfe14e7725647160a7fb4205c0730153661c37eaec6357346a
    restart: on-failure
    ports:
      - "${APP_HOMEBRIDGE_PORT}:8581"
    volumes:
      - ${APP_DATA_DIR}/data/homebridge:/homebridge
    environment:
      HOMEBRIDGE_CONFIG_UI : 1
      HOMEBRIDGE_CONFIG_UI_PORT: $APP_HOMEBRIDGE_PORT
    networks:
      default:
        ipv4_address: $APP_HOMEBRIDGE_IP
